spring.application.name=El Bucle Infinito

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:bucleinfinito
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin123

# Consola H2
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/h2/schema.sql
spring.sql.init.data-locations=classpath:db/h2/data.sql
spring.sql.init.encoding=UTF-8

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework=INFO
