CREATE TABLE IF NOT EXISTS tipos_mesa (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS comidas_especiales (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS mesas (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero    INTEGER NOT NULL,
    capacidad INTEGER NOT NULL,
    activa    BOOLEAN NOT NULL DEFAULT TRUE,
    seccion   VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS clientes (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(30) NOT NULL,
    apellido  VARCHAR(30) NOT NULL,
    telefono  VARCHAR(20),
    direccion VARCHAR(255),
    ciudad    VARCHAR(80),
    vip       BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS reservas (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia                 DATE NOT NULL,
    hora                TIME NOT NULL,
    cantidad_personas   INTEGER NOT NULL,
    estado              VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    cliente_id          INTEGER NOT NULL,
    mesa_id             INTEGER,
    tipo_mesa_id        INTEGER,
    comida_especial_id  INTEGER,
    FOREIGN KEY (cliente_id)         REFERENCES clientes(id),
    FOREIGN KEY (mesa_id)            REFERENCES mesas(id),
    FOREIGN KEY (tipo_mesa_id)       REFERENCES tipos_mesa(id),
    FOREIGN KEY (comida_especial_id) REFERENCES comidas_especiales(id)
);

CREATE TABLE IF NOT EXISTS visitas (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_visita   DATE NOT NULL,
    notas          VARCHAR(255),
    codigo_interno VARCHAR(50),
    reserva_id     INTEGER NOT NULL,
    FOREIGN KEY (reserva_id) REFERENCES reservas(id)
);
